### ISSUE TITLE
Questions about image inpainting

### ISSUE THREAD

**Issue by xhh232018** [yu45020/Text_Segmentation_Image_Inpainting#2]
Hi, I am the one who reply you in the Generative Image Inpainting(Deepfill V2). Can u give me your email address? I am desired to communicate with you. I am a master student in USC.
BTW, if you have a wechat number, you can send friend request to me. My ID is xhh_0914.
Looking forward to your reply.

Best,
Hanhua Xiao

**Comment by yu45020** [comment]
I have added you over wechat.

Recommend to delete your personal information.
