### ISSUE TITLE
可以试试用gan来inpaint试试

### ISSUE THREAD

**Issue by zhouhang95** [yu45020/Text_Segmentation_Image_Inpainting#4]
这有个工作可以看看
Attentive Generative Adversarial Network for Raindrop Removal from A Single Image

**Comment by yu45020** [comment]
那篇论文之前看过， 不过图片修复还是偏向于 [Image Inpainting for Irregular Holes Using Partial Convolutions](https://arxiv.org/abs/1804.07723) 和 deepfill系列的[Generative Image Inpainting with Contextual Attention](https://github.com/JiahuiYu/generative_inpainting).  我对gan的理解还很浅，尝试过复现前面deepfill的gan，用10来张图训练了几个小时都不出效果。后来听所[gan的训练很耗时间](https://github.com/JiahuiYu/generative_inpainting/issues/62#issuecomment-406930497)就怂了。 GPU租不起。

**Comment by zhouhang95** [comment]
话说十来张图有点少吧
另一个waifu的项目我看你完成了不少工作 没用GPU吗

**Comment by yu45020** [comment]
正式训练前我都会用一个batch尝试，另一个batch作测试。 模型如果写的正确的话，肯定能overfit。 顺手大致估计完整数据下的loss走向和耗时， 还可以测出 cyclical learning rate 的上限。 能省不少时间。 

GPU是租google的， p-100 0.43 一小时。 免费的credit快用完了  >< 。

waifu2x其实是用来熟悉PyTorch的， 还手贱做了个去照片手抖的模型没放上来。

**Comment by yu45020** [comment]
欢迎继续提供各种建议，设想。 这issue我关咯
