### ISSUE TITLE
这个文本掩码数据是怎么得到的？

### ISSUE THREAD

**Issue by freekoy** [yu45020/Text_Segmentation_Image_Inpainting#6]
下载了danbooru这个数据，没有去掉文本的图像？？想要做类似的东西，从漫画中检测出对话气泡，个人标注，工程量庞大，想知道类似的数据，或者解决方案

**Comment by yu45020** [comment]
可能是我写的不清楚， 最近都没空来管这项目了。  ><
数据是在某站下的，原本+text_clean 的本。 模型出来的效果就是模拟手动去字的结果，并没有检测气泡的能力。 如果打算检测气泡，推荐manga109。 去官网申请就可以了， 里面都有详细标注。不过，字体的标注不少掩盖了了文字框和背景，这对于去字来说增加了后期工作量。我找不出好的方法直接丢进模型里面用。 

找汉化组合作是最快的方法，可惜导出无字版需要额外的功夫。 不知道你有没有门路？

**Comment by freekoy** [comment]
manga109申请了好久，都过去一周了，没人回复我。关于导出无字版的，有一个想法，用彩色漫画，然后，基本上对话框都是白色的，opencv应该可以提取白色，你认为这个想法可行否

**Comment by yu45020** [comment]
@freekoy . Manga109 拿到手了? 昨天跟知情人士聊过，貌似用学校邮箱申请，并且附上详细的模型介绍或者思路，就可以拿到了。不过我那时候也等了4，5天。 

你的想法我用少量数据尝试了一下，可行。 不过适用面会变得很窄，而且也有对话框是透明的，或者根本没有对话框。还是无解。

**Comment by freekoy** [comment]
manga109依然没回应，找了个替代的数据库，效果还可以
[https://github.com/freekoy/comic-textboxs](url)
其实觉得你可以加多一个上色模型或模块，输入一张黑白漫画，上色成彩色漫画，再来去掉文本
对话框是透明和没有对话框的，只能上目标检测再什么了，类似ocr

**Comment by yu45020** [comment]
类似的设计在最初就像过了，做成类似mask rcnn 的 two stage object detector。 问题有3个问题： 如果用户没有gpu，那么处理时间会很长； 有不少文字是没有文字框的， 而且汉化组们也只负责修图，不会加框标注；超长的训练时间，GPU的钱哪里来 Orz

comic-textbox 应该可以用，或者直接用manga109的数据，同时把里面的字都去掉（30K+的图），那么就有了很优秀的训练数据。 

而我的方案就很直接，反正只需要判断某一部分的像素是否文字，就将整个问题转换成判断1/0的问题。 生成的不规则掩码就交给后续的图片修复模型处理。整个流程思路应该是很流畅的。

**Comment by freekoy** [comment]
最近看了一下GAN,觉得这个方案可能比现在的Text_Segmentation_Image_Inpainting要好很多，而且可以人为生成数据
就是训练一个类似去马赛格（去文字）的模型
另外，你有manga109 dataset?能分享给我吗

**Comment by yu45020** [comment]
请问是什么GAN？ 隔壁还有一个deep fill2 的gan，但训练时间很长，租GPU不现实。
manga109的数据不能分享： [“Users are requested to not pass the data set to a third party”](http://www.manga109.org/en/)

**Comment by FantasyJXF** [comment]
> 请问是什么GAN？ 隔壁还有一个deep fill2 的gan，但训练时间很长，租GPU不现实。
> manga109的数据不能分享： [“Users are requested to not pass the data set to a third party”](http://www.manga109.org/en/)

@yu45020    这么实在的嘛？ 有数据集还是可以共享一下一起研究啊。

@freekoy  哥们漫画对话框检测做的怎么样了？

**Comment by yu45020** [comment]
@FantasyJXF 這是學術研究的規範和底綫，必須遵守。

**Comment by GuilmK** [comment]
“数据是在某站下的，原本+text_clean 的本。”能告知一下这个网站吗？

**Comment by jerrywyn** [comment]
> 下载了danbooru这个数据，没有去掉文本的图像？？想要做类似的东西，从漫画中检测出对话气泡，个人标注，工程量庞大，想知道类似的数据，或者解决方案

danbooru是用官网提供的bt下载吗，好像下载不了啊（我按他提示的用了transmission下载器、以及最新版本的qbittorrent，都下载不动），有没有别的数据源呢

**Comment by yu45020** [comment]
@jerrywyn 
我用Rsync下的，更加方便。 不过请注意友好地是用流量

https://www.gwern.net/Danbooru2020#rsync

**Comment by jerrywyn** [comment]
非常感谢，我也成功下载了。但是好像图片质量不是很好hhhh，想问一下这个项目作者说的text_clean的数据是在哪个网站下载的？


非常感谢您的热心帮助！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yu45020/Text_Segmentation_Image_Inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yu45020/Text_Segmentation_Image_Inpainting] 这个文本掩码数据是怎么得到的？ (#6)





 
@jerrywyn
 我用Rsync下的，更加方便。 不过请注意友好地是用流量
 
https://www.gwern.net/Danbooru2020#rsync
