### ISSUE TITLE
some questions about your models

### ISSUE THREAD

**Issue by dianxin556** [yu45020/Text_Segmentation_Image_Inpainting#7]
hi, you said you have trained a model which use depth wise convlution instead of norm conv. Is that mean you refered to mobilenet constructure？and what did you do in decoder about that? If it is convenient for you, could you give me your email or other contact information？thanks a lot!

**Comment by Kevinkevin189** [comment]
Is this project been banned? Or what's the reason there is no more progress on it?

**Comment by yu45020** [comment]
@dianxin556 More accurately, I trained a Mobile net V2. The [decoder](https://github.com/yu45020/Text_Segmentation_Image_Inpainting/blob/41d08b936323ca352af24f9284d6b593b68dc25c/models/text_segmentation.py#L18) was similar to the Xecption model. Parts of the model has been rewritten, though I haven't push them to this repo yet. You may contact me via my username + gmail

@Kevinkevin189 **I have run out of GPU credit** in Google cloud.  Orz.  And I am quite busy in the past few months. I might be able to find time and restart the project during the new year holiday, hopefully.

**Comment by Kevinkevin189** [comment]
Hope ur project goes well.Besides,I'm confused about ur inpainting settings. In ur project frontpage, the inpaint part where u describe ur partival residual block, it seems u chose random mask to train the inpaint part.But u goal is to remove the text on comic scenes which should use text mask in training process,which is better?random mask or text mask?any differences?
